##
# Label incoming pull requests according to configuration in .github/labeler.yml
##

name: Apply labels

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # See documentation: https://github.com/actions/labeler
      - uses: actions/labeler@4.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
