##
# Publish new action tag(s) for downstream consumption
##

name: Publish

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn workspaces foreach run package
      - uses: iacobfred/release-typescript-action@v1
        with:
          increment-level: patch
