##
# Publish new action tag(s) for downstream consumption
##
name: Publish

# Manual or automatic release
on:
  # release:
  #   types: [published, edited]
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Release with semantic tag like v1.0.3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: int128/release-typescript-action@v1
