##
# Publish new action tag(s) for downstream consumption
##
name: Publish

# Manual or automatic release
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - run: yarn workspaces foreach run package
      - uses: iacobfred/release-typescript-action@v1
        with:
          increment-level: patch
